name: Build and Push Docker Image

on:
  push:
    branches:
      - main # O build vai rodar toda vez que você fizer um push na main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instala o QEMU, necessário para compilar para ARM (sua VPS) na máquina Intel do GitHub
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configura o Buildx, a ferramenta que permite o build multi-arquitetura
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Faz login no Docker Hub usando os Secrets que você configurou
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Faz o build usando o Dockerfile correto e envia para o Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/documenso:latest
